//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        public int codcli { get; set; }
        public string nomcli { get; set; }
        public string dircli { get; set; }
        public decimal numtel { get; set; }
        public string correo { get; set; }
        public int edad { get; set; }
    }
}
